### ISSUE TITLE
Image could not be loaded.

### ISSUE THREAD

**Issue by Auditormadness9** [krikienoid/flagwaver#60]
![image](https://user-images.githubusercontent.com/71278545/176460991-fe3afc2b-7041-4de7-9ca5-3dab46a3b262.png)

**Comment by krikienoid** [comment]
Hello there, can you provide the image link?

**Comment by Auditormadness9** [comment]
> Hello there, can you provide the image link?

sure.

http://stateless-nations.com/files/pasted-graphic-12-2.jpg

**Comment by krikienoid** [comment]
It looks like the image is getting blocked due to security issues. The stateless-nations.com website is not on SSL so FlagWaver is not able load any images from that website. This is not an issue that can be solved by FlagWaver. I would contact whoever manages that site and recommend they enable SSL on their website.
<img width="1241" alt="Screen Shot 2022-07-01 at 8 47 36 AM" src="https://user-images.githubusercontent.com/8528227/176897896-ca9c8072-d905-4c33-a88e-e9afc9226ad7.png">

**Comment by Auditormadness9** [comment]
Okay thanks. And what about Reddit? Images from Reddit don't work either.

**Comment by krikienoid** [comment]
Reddit does not allow images to be loaded over CORS, again not something that FlagWaver can solve. Every website has their own policies that may or may not allow images to be loaded and used externally by a website like FlagWaver.

**Comment by omerien** [comment]
You still can reupload the image somewhere else (GitHub or other) and use the image from there.
