### ISSUE TITLE
Use flagwaver in my login page and set Image as default. 

### ISSUE THREAD

**Issue by naghizadeh7000** [krikienoid/flagwaver#7]
Hi krikienoid,
I really liked flagwaver and I want to use it in one of my pages. But I have a problem with the flag picture. I hid the controls. But couldn't set my image as default. (Not by URL or File Uploading).

When I download your code the page doesn't run the flag picture. It just has the Material.
it would be kind of you to answer ASAP. 
Regards.
info@mnaghizadeh.com

**Comment by krikienoid** [comment]
Hi,

Glad you liked the program.

It's very difficult for me to help you with this issue if you do not have any code for me to look at.

Most likely, the image is getting blocked due to the browser's security policy. If that is the case, you will want to make sure that the image is on the same host as your webpage, or if that's not possible, on a host that allows the image to be loaded with CORS.

Hope that helps.
